rule all:
    input:
        "out/figure1.pdf"

rule sim_naive:
    input:
        "sim.R"
    output:
        "rds/sim-naive.rds"
    shell:
        "Rscript sim.R naive {output}"

rule sim_split:
    input:
        "sim.R"
    output:
        "rds/sim-split.rds"
    shell:
        "Rscript sim.R split {output}"

rule figure:
    input:
        script = "figure.R",
        rds = ["rds/sim-naive.rds", "rds/sim-split.rds"]
    output:
        "out/figure1.pdf"
    shell:
        "Rscript {input.script} {output} {input.rds}"
